print('the weather is nice today')
print('Rearrange clothes in my room')
print('my city is tbilisi')
print('girls painted hers parethissis')
print('I am wearing vearity clothes')
print('this quastion is inccorect')
print('I lose in game')
print('I select clothes')
print('I tell true in my family')